### ISSUE TITLE
Cannot read property 'minBarLength' of undefined.

### ISSUE THREAD

**Issue by gkane6** [datavisyn/chartjs-chart-box-and-violin-plot#53]
Hi everyone! Could you guide me on how to use this with reactjs.

in  `chart.js`  file
```js
import React, { useEffect } from 'react';
import { Chart as Graph } from 'chart.js';
import 'chartjs-chart-box-and-violin-plot/build/Chart.BoxPlot.js';

export default React.memo(function Chart({ data, options, type }) {
    const chartRef = React.useRef(null);

    useEffect(() => {
        const { current } = chartRef;
        const chartContext = current.getContext('2d');

        new Graph(chartContext, {
            type,
            data,
            options,
        });
    }, [chartRef, data, options, type]);

    return (
        <>
            <canvas id={`${type}-graph`} ref={chartRef} className="Chart" />
        </>
    )})
```

 In `ChartBoxPlot.js` file 
```js
import React from 'react';
import Chart from  './Chart';

const ChartBoxPlot = ({ data, options }) => {
    return (
          <div>
            <div className="Bar">
                <Chart data={data} options={options} type="boxplot" />
            </div>
        </div>);
};
export default ChartBoxPlot;`
```
This is what I get in the console 
```
Cannot read property 'minBarLength' of undefined
TypeError: Cannot read property 'minBarLength' of undefined
    at ChartElement.calculateBarValuePixels (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:43171:30)
    at ChartElement._updateElementGeometry (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:43066:20)
    at ChartElement._updateElementGeometry (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:55359:62)
    at ChartElement.updateElement (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:43051:6)
    at ChartElement.updateElement (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:55236:53)
    at ChartElement.update (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:43024:7)
    at ChartElement._update (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:41960:6)
    at ChartElement.reset (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:41862:8)
    at http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:47721:16
    at Object.each (http://localhost:64876/vendors~main.88ed1bbe4abec7a73360.bundle.js:40354:9)
```

**Comment by sgratzl** [comment]
Hi, can you post examples values that you used for the properties? especially: `data` and `options`

**Comment by gkane6** [comment]
Hello @sgratzl , I used same as your codepen example https://codepen.io/sgratzl/pen/QxoLoY

**Comment by sgratzl** [comment]
hm. I currently playing with https://codesandbox.io/s/runtime-https-xqyve and I have no problem

**Comment by gkane6** [comment]
<img width="670" alt="Screen Shot 2019-10-30 at 4 46 04 PM" src="https://user-images.githubusercontent.com/35712548/67897552-03606c00-fb35-11e9-960f-129b5af57e0e.png">

**Comment by sgratzl** [comment]
what versions of the plugin and chart.js are you using?

**Comment by diego-marinic** [comment]
I have the same problem, currently using Chart.js 2.9.1.
CodePen example (https://codepen.io/sgratzl/pen/QxoLoY) breaks when updating the Chart.js reference to 2.9.1 so probably some change in this version breaks compatibility

**Comment by diego-marinic** [comment]
Adding the "minBarLength" property to the datasets avoids this exception but then the following happens:
```
Chart.bundle.js:6244 Uncaught TypeError: Cannot read property 'skip' of undefined
    at parseVisibleItems (Chart.bundle.js:6244)
    at getIntersectItems (Chart.bundle.js:6260)
    at indexMode (Chart.bundle.js:6321)
    at Chart.getElementsAtEventForMode (Chart.bundle.js:9504)
    at Chart.handleEvent (Chart.bundle.js:9741)
    at Chart.eventHandler (Chart.bundle.js:9688)
    at listener (Chart.bundle.js:9621)
    at HTMLCanvasElement.proxies.<computed> (Chart.bundle.js:7351)
```

**Comment by sgratzl** [comment]
good catch. I filled a PR which should fix it. in the meanwhile you should be able to install the branch directly as in 

```
npm i datavisyn/chartjs-chart-box-and-violin-plot#sgratzl/bugfix
```

**Comment by gkane6** [comment]
> what versions of the plugin and chart.js are you using?

`"chart.js": "^2.9.1",
        "chartjs-chart-box-and-violin-plot": "^2.1.0",`

**Comment by sgratzl** [comment]
thx, it already has been resolved. I don't know why codesandbox/parcel insisted on using 2.8.0 even it breaks with 2.9.1

**Comment by lehnerchristian** [comment]
did you get any error messages, @gkane6 ?

**Comment by sgratzl** [comment]
> Hi! I installed that branch, it fixed the error but data is not showing now.🤷🏿‍♀️

I just pushed another fix, can you rerun `npm i datavisyn/chartjs-chart-box-and-violin-plot#sgratzl/bugfix` and try again?

**Comment by gkane6** [comment]
> did you get any error messages, @gkane6 ?

didn't get error messages. But it is now fix with that push👆🏿👆🏿

**Comment by gkane6** [comment]
I am having the initial issue again with the merged version 🤷🏿‍♀️.
